export type AncoreCategorie = "ALERTĂ" | "BLOCATĂ" | "OBOSEALĂ" | "LINIȘTIRE" | "CONECTARE";
export type AncoreNivel = "SOS" | "REGLEAZĂ" | "APROFUNDEAZĂ";

export interface AncoreExercise {
  id: string;
  nume: string;
  categorie: AncoreCategorie;
  nivel: AncoreNivel;
  energie: string;
  context: string[];
  durata_sec: number;
  descriere_scurta: string;
  trigger_text: string;
  pasi: string[];
  ancora_text: string;
  inchidere_text: string;
  v1_selectat: boolean;
  prioritate: number;
  stare_interna: string;
  ochi_deschisi: boolean | null;
  obiectiv_neurofiziologic: string;
  surse_teoretice: string;
  contraindicatii: string;
}

export const CATEGORIE_CONFIG: Record<AncoreCategorie, { bg: string; text: string; border: string; label: string }> = {
  "ALERTĂ":    { bg: "#E8EEF2", text: "#2E4A5E", border: "#B8CDD8", label: "Alertă" },
  "BLOCATĂ":   { bg: "#EDEDED", text: "#3A3A3A", border: "#C8C8C8", label: "Blocată" },
  "OBOSEALĂ":  { bg: "#FBF4E8", text: "#6B4C1E", border: "#E8D8B8", label: "Oboseală" },
  "LINIȘTIRE": { bg: "#F5EBE8", text: "#6B2E22", border: "#E0C8C0", label: "Liniștire" },
  "CONECTARE": { bg: "#E8F0E5", text: "#1E5C30", border: "#B8D8B0", label: "Conectare" },
};

export const NIVEL_CONFIG: Record<AncoreNivel, { bg: string; text: string; label: string }> = {
  "SOS":          { bg: "#FEE2E2", text: "#991B1B", label: "SOS" },
  "REGLEAZĂ":     { bg: "#E0E7FF", text: "#3730A3", label: "Reglează" },
  "APROFUNDEAZĂ": { bg: "#D1FAE5", text: "#065F46", label: "Aprofundează" },
};

export const ANCORE_DATA: AncoreExercise[] = [
  {
    id: "M-001", nume: "Mâinile pe ceva rece", categorie: "ALERTĂ", nivel: "SOS",
    energie: "30s", context: ["Acasă", "Birou", "Public"], durata_sec: 25,
    descriere_scurta: "Pune palmele pe ceva rece și numeri lent până la cincisprezece.",
    trigger_text: "Inima bate repede. Gândurile aleargă.",
    pasi: ["Du-te la ceva rece - robinet, frigider, un pahar.", "Așază palmele pe suprafața rece.", "Stai acolo cât numeri lent până la cincisprezece."],
    ancora_text: "Lasă-ți atenția să urmărească senzația de răcoare adusă de inspir.",
    inchidere_text: "Atât. Corpul a primit semnalul.",
    v1_selectat: true, prioritate: 1, stare_interna: "Furtună", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Activare mammalian diving reflex; switch rapid parasympathetic via stimulare vag trigeminală",
    surse_teoretice: "Peter Levine; Deb Dana; Stanford diving reflex research",
    contraindicatii: "Raynaud, sensibilitate severă la frig",
  },
  {
    id: "M-002", nume: "Lasă maxilarul", categorie: "ALERTĂ", nivel: "SOS",
    energie: "10s", context: ["Acasă", "Birou", "Public", "Mașină", "Pat"], durata_sec: 15,
    descriere_scurta: "Lași maxilarul să se desprindă, limba coboară, buzele rămân puțin întredeschise.",
    trigger_text: "Strângi din dinți și nici nu-ți dai seama.",
    pasi: ["Lasă maxilarul să se desprindă.", "Limba se desprinde de cerul gurii.", "Buzele rămân puțin întredeschise."],
    ancora_text: "Simte greutatea bărbiei. Doar atât.",
    inchidere_text: "Maxilarul poate purta tensiune fără să ne dăm seama. Acum îl lași să se relaxeze puțin.",
    v1_selectat: true, prioritate: 1, stare_interna: "Furtună", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Relaxare musculară temporomandibulară; reducere tonus simpatic facial",
    surse_teoretice: "Peter Levine; Stephen Porges", contraindicatii: "TMJ acut",
  },
  {
    id: "M-003", nume: "Coboară pe expir", categorie: "ALERTĂ", nivel: "SOS",
    energie: "30s", context: ["Acasă", "Birou", "Public", "Mașină", "Pat"], durata_sec: 30,
    descriere_scurta: "Inspiri firesc; la fiecare expir lași o secundă în plus. De patru ori.",
    trigger_text: "Pieptul e strâns. Respirația e scurtă.",
    pasi: ["Inspiri pe nas, firesc.", "La expir, lași o secundă în plus. O singură secundă mai lungă.", "Repeți de patru ori."],
    ancora_text: "Nu trebuie să urmărești tot. Doar expirul.",
    inchidere_text: "Expirul lung face singur ce trebuie. Tu doar îl lași să se întâmple.",
    v1_selectat: true, prioritate: 1, stare_interna: "Furtună", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Tonus vagal via expir prelungit; sympathovagal balance",
    surse_teoretice: "Stephen Porges; Brown & Gerbarg",
    contraindicatii: "Evitați în hiperventilație activă sau panică acută cu senzație de leșin",
  },
  {
    id: "M-004", nume: "Un mmm lung", categorie: "ALERTĂ", nivel: "REGLEAZĂ",
    energie: "1min", context: ["Acasă"], durata_sec: 45,
    descriere_scurta: "La expir faci un sunet de mmm lung, ca un bondar. De trei ori.",
    trigger_text: "Mintea e zgomotoasă. Nu se oprește.",
    pasi: ["Închizi ochii, dacă vrei.", "Inspiri.", "La expir, faci un sunet de mmm lung, ca un bondar.", "De trei ori."],
    ancora_text: "Observă ce simți acum în zona capului. În piept.",
    inchidere_text: "Vibrația ajunge direct unde nu ajung cuvintele.",
    v1_selectat: false, prioritate: 2, stare_interna: "Furtună", ochi_deschisi: false,
    obiectiv_neurofiziologic: "Stimulare vag prin vibrație nazo-faringiană; Bhramari pranayama",
    surse_teoretice: "Bhramari pranayama (tradiție yogică); principiul vibrației vagale (Porges)",
    contraindicatii: "infecție gât/sinusuri",
  },
  {
    id: "M-005", nume: "Strânge tot, apoi lasă", categorie: "ALERTĂ", nivel: "SOS",
    energie: "30s", context: ["Acasă", "Birou", "Public", "Mașină"], durata_sec: 20,
    descriere_scurta: "Strângi tot corpul ferm șapte secunde, apoi lași brusc.",
    trigger_text: "Tensiunea s-a strâns în pumni, umeri, picioare.",
    pasi: ["Strângi tot, ferm - pumni, umeri, picioare. Șapte secunde.", "Apoi lași brusc.", "Încă o dată, dacă vrei."],
    ancora_text: "Diferența dintre cele două momente.",
    inchidere_text: "Corpul tău știe să elibereze. Tu doar îi dai voie.",
    v1_selectat: false, prioritate: 1, stare_interna: "Furtună", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Progressive muscle release; descărcare neuromusculară",
    surse_teoretice: "Jacobson PMR; Peter Levine",
    contraindicatii: "Evitați în leziuni musculare acute, hipertensiune necontrolată",
  },
  {
    id: "M-006", nume: "Cinci lucruri dintr-o culoare", categorie: "ALERTĂ", nivel: "SOS",
    energie: "30s", context: ["Acasă", "Birou", "Public", "Mașină"], durata_sec: 20,
    descriere_scurta: "Alege o culoare și lasă-ți privirea să descopere cinci locuri în care ea apare în jurul tău.",
    trigger_text: "Anxietatea urcă. Te pierzi în interior.",
    pasi: ["Privești în jur. Alegi o culoare și observă cum începe să apară, discret, în jurul tău. Găsește cinci exemple.", "Le spui în gând, pe rând."],
    ancora_text: "Mișcarea ochilor te scoate, încet, încet, din interior.",
    inchidere_text: "Atât. Camera e tot acolo, în jurul tău.",
    v1_selectat: true, prioritate: 1, stare_interna: "Furtună", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Orientare vizuală; reducere interocepție anxiogenă",
    surse_teoretice: "Deb Dana; Peter Levine", contraindicatii: "deficiențe vizuale severe",
  },
  {
    id: "M-007", nume: "Tălpile în podea", categorie: "ALERTĂ", nivel: "SOS",
    energie: "30s", context: ["Acasă", "Birou", "Public", "Mașină", "Pat"], durata_sec: 30,
    descriere_scurta: "Apeși tălpile în podea și le simți. Nu schimbi nimic, doar observi sprijinul.",
    trigger_text: "Te simți ridicat de pe pământ. Puțin disociat.",
    pasi: ["Apeși ambele tălpi în podea. Nu împingi - doar le simți.", "Stai așa douăzeci de secunde."],
    ancora_text: "Greutatea pe călcâie. Pământul care e deja acolo.",
    inchidere_text: "Poate că nu trebuie să te susții singur în întregime. Lasă ceea ce te susține să preia puțin din greutate.",
    v1_selectat: true, prioritate: 1, stare_interna: "Furtună", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Grounding proprioceptiv; activare interocepție de suport",
    surse_teoretice: "Peter Levine; Deb Dana", contraindicatii: "amputație/durere severă picioare",
  },
  {
    id: "M-008", nume: "Palmele calde pe spate", categorie: "ALERTĂ", nivel: "REGLEAZĂ",
    energie: "1min", context: ["Acasă"], durata_sec: 60,
    descriere_scurta: "Palmele calde pe zona joasă a spatelui, peste rinichi. Un minut.",
    trigger_text: "Adrenalina circulă. Nu poți sta locului.",
    pasi: ["Îți încălzești palmele, frecându-le puțin.", "Le așezi pe zona joasă a spatelui, peste rinichi.", "Stai așa un minut."],
    ancora_text: "Căldura care trece prin haine. Spre dedesubt.",
    inchidere_text: "Corpul a primit semnal că poate încetini.",
    v1_selectat: false, prioritate: 2, stare_interna: "Furtună", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Auto-atingere blândă; co-reglare cu sine; reducere cortizol",
    surse_teoretice: "Peter Levine; Deb Dana", contraindicatii: "traumă tactilă, evita auto-atingerea",
  },
  {
    id: "M-009", nume: "Privirea, pe ceva departe", categorie: "ALERTĂ", nivel: "REGLEAZĂ",
    energie: "30s", context: ["Acasă", "Birou"], durata_sec: 20,
    descriere_scurta: "Lași privirea să cadă pe ceva îndepărtat, fără să cauți nimic.",
    trigger_text: "Te-ai îngustat. Focusat prea mult timp în același loc.",
    pasi: ["Privești prin fereastră.", "Lași privirea să cadă pe ceva îndepărtat.", "Nu cauți nimic anume."],
    ancora_text: "Marginile câmpului vizual. Ce vezi fără să te uiți direct.",
    inchidere_text: "Ochii s-au odihnit. Restul te urmează.",
    v1_selectat: true, prioritate: 2, stare_interna: "Forfotă", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Privire panoramică; ventral vagal cue; relaxare oculară",
    surse_teoretice: "Andrew Huberman; Peter Levine", contraindicatii: "nu există fereastră → folosește obiect îndepărtat",
  },
  {
    id: "M-010", nume: "O înghițitură de apă", categorie: "ALERTĂ", nivel: "SOS",
    energie: "1min", context: ["Acasă", "Birou"], durata_sec: 45,
    descriere_scurta: "O înghițitură de apă, băută foarte încet și conștient.",
    trigger_text: "Iritare difuză. Nu știi de unde.",
    pasi: ["Iei un pahar cu apă.", "Bei o înghițitură foarte lent.", "Conștient, fără să te grăbești."],
    ancora_text: "Senzația apei pe limbă. În gât. Coborând.",
    inchidere_text: "Când încetinești puțin, chiar și un gest obișnuit poate căpăta o altă senzație.",
    v1_selectat: true, prioritate: 1, stare_interna: "Forfotă", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Mindful drinking; interoceptive awareness via deglutiție",
    surse_teoretice: "Anālayo Satipatthana; Lisa Feldman Barrett", contraindicatii: "tulburări înghițire",
  },
  {
    id: "M-011", nume: "Întinde-te ca după somn", categorie: "OBOSEALĂ", nivel: "REGLEAZĂ",
    energie: "30s", context: ["Acasă", "Pat"], durata_sec: 25,
    descriere_scurta: "Te întinzi ca după somn, brațele sus; dacă vine un căscat, îl lași.",
    trigger_text: "Corpul e amorțit. Mintea agitată.",
    pasi: ["Te întinzi ca după somn. Brațele sus, spatele puțin arcuit.", "Dacă vine un căscat, îl lași să vină."],
    ancora_text: "Plăcerea de a te întinde. Care e deja acolo.",
    inchidere_text: "Uneori, corpul caută singur mai mult spațiu. O întindere blândă este unul dintre modurile prin care se reorganizează.",
    v1_selectat: true, prioritate: 2, stare_interna: "Forfotă", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Pandiculation; activare fasciei; reset autonom",
    surse_teoretice: "Peter Levine; Thomas Hanna", contraindicatii: "leziuni umăr/spate acute",
  },
  {
    id: "M-012", nume: "Atinge o textură", categorie: "BLOCATĂ", nivel: "SOS",
    energie: "30s", context: ["Acasă", "Birou", "Public"], durata_sec: 30,
    descriere_scurta: "Atingi cu atenție o textură interesantă, treizeci de secunde.",
    trigger_text: "Te simți plat. Scos din simțuri.",
    pasi: ["Găsești o textură interesantă - lemn, țesătură, o frunză.", "O atingi cu atenție timp de treizeci de secunde."],
    ancora_text: "Detaliile pe care le simți cu vârful degetelor.",
    inchidere_text: "Pielea are mai mulți receptori decât orice alt organ. O folosești ca să revii.",
    v1_selectat: false, prioritate: 1, stare_interna: "Forfotă", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Senzație tactilă; reglare interoceptivă; orientare tangibilă",
    surse_teoretice: "Lisa Feldman Barrett; Peter Levine", contraindicatii: "alodinie tactilă",
  },
  {
    id: "M-013", nume: "Trei respirații", categorie: "ALERTĂ", nivel: "SOS",
    energie: "30s", context: ["Acasă", "Birou", "Public", "Mașină", "Pat"], durata_sec: 30,
    descriere_scurta: "Trei respirații conștiente. Doar trei.",
    trigger_text: "Două minute între task-uri.",
    pasi: ["Trei respirații conștiente.", "Doar trei. Nu mai multe."],
    ancora_text: "Cum se schimbă, subtil, ceva între prima și a treia.",
    inchidere_text: "Trei respirații nu rezolvă totul. Dar resetează ceva mic. E suficient pentru moment.",
    v1_selectat: false, prioritate: 1, stare_interna: "Forfotă", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Mini-pauză parasympatică; ruptură de pattern automat",
    surse_teoretice: "BJ Fogg tiny habits; Brown & Gerbarg", contraindicatii: "niciuna",
  },
  {
    id: "M-014", nume: "Zece pași și înapoi", categorie: "BLOCATĂ", nivel: "REGLEAZĂ",
    energie: "30s", context: ["Acasă", "Birou"], durata_sec: 30,
    descriere_scurta: "Te ridici și faci zece pași, apoi zece înapoi.",
    trigger_text: "Ai stat prea mult. Energia stagnează.",
    pasi: ["Te ridici.", "Zece pași oriunde.", "Apoi zece înapoi."],
    ancora_text: "Tălpile care primesc, alternativ, toată greutatea.",
    inchidere_text: "Mișcarea descarcă ce s-a strâns. Nu trebuie să fie mai mult de atât.",
    v1_selectat: false, prioritate: 2, stare_interna: "Forfotă", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Bilateral stimulation prin mers; activare proprioceptivă",
    surse_teoretice: "Peter Levine", contraindicatii: "probleme echilibru/mers",
  },
  {
    id: "M-015", nume: "Cel mai îndepărtat sunet", categorie: "ALERTĂ", nivel: "REGLEAZĂ",
    energie: "30s", context: ["Acasă", "Birou", "Public", "Mașină"], durata_sec: 30,
    descriere_scurta: "Cauți cel mai îndepărtat sunet pe care îl auzi.",
    trigger_text: "Mintea s-a blocat într-un loop.",
    pasi: ["Închizi ochii, dacă vrei.", "Cauți cel mai îndepărtat sunet pe care îl auzi."],
    ancora_text: "Distanța dintre tine și acel sunet.",
    inchidere_text: "Uneori, atenția îndreptată către sunete poate crea puțin mai mult loc pentru respirație și prezență.",
    v1_selectat: false, prioritate: 2, stare_interna: "Forfotă", ochi_deschisi: false,
    obiectiv_neurofiziologic: "Open awareness auditivă; expansie atențională",
    surse_teoretice: "Anālayo Satipatthana; tradiție mindfulness", contraindicatii: "deficiențe auditive severe",
  },
  {
    id: "M-016", nume: "Un milimetru de zâmbet", categorie: "CONECTARE", nivel: "SOS",
    energie: "10s", context: ["Acasă", "Birou", "Public", "Mașină"], durata_sec: 15,
    descriere_scurta: "Lași colțurile gurii să urce un milimetru. Doar o relaxare.",
    trigger_text: "Fața ta e încordată. Și nici nu știi.",
    pasi: ["Lași colțurile gurii să urce un milimetru.", "Atât. Nu un zâmbet adevărat - doar o relaxare."],
    ancora_text: "Cum se relaxează, cumva, și restul feței odată cu ele.",
    inchidere_text: "Fața e și ea o ușă către sistemul nervos.",
    v1_selectat: false, prioritate: 1, stare_interna: "Forfotă", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Facial feedback via zigomatic; semnal ventral vagal",
    surse_teoretice: "Stephen Porges; facial feedback hypothesis", contraindicatii: "paralizie facială",
  },
  {
    id: "M-017", nume: "Un tremur ușor", categorie: "BLOCATĂ", nivel: "REGLEAZĂ",
    energie: "30s", context: ["Acasă"], durata_sec: 30,
    descriere_scurta: "În picioare, lași genunchii să tremure ușor, treizeci de secunde.",
    trigger_text: "Te simți departe. Într-o ceață.",
    pasi: ["Stai în picioare.", "Lași genunchii să tremure ușor.", "Lași tremurul să urce. Treizeci de secunde."],
    ancora_text: "Senzația de viu care revine, încet, în picioare, în mâini.",
    inchidere_text: "Tremuratul este unul dintre modurile prin care corpul poate elibera energia rămasă în tensiune.",
    v1_selectat: false, prioritate: 2, stare_interna: "Ceață", ochi_deschisi: true,
    obiectiv_neurofiziologic: "TRE; descărcare via tremor neurogen; ieșire din freeze",
    surse_teoretice: "David Berceli TRE; Peter Levine",
    contraindicatii: "Evitați după comotie cerebrală recentă, vertij sever, leziuni picioare",
  },
  {
    id: "M-018", nume: "Capul, încet, în jur", categorie: "BLOCATĂ", nivel: "REGLEAZĂ",
    energie: "30s", context: ["Acasă", "Birou", "Mașină"], durata_sec: 25,
    descriere_scurta: "Întorci capul încet la dreapta, apoi la stânga, privind din nou camera.",
    trigger_text: "Ești într-o bulă. Nu chiar prezent.",
    pasi: ["Întorci capul încet la dreapta.", "Apoi încet la stânga.", "Privești camera ca pentru prima dată."],
    ancora_text: "Ce e nou de văzut, deși ai mai fost aici.",
    inchidere_text: "Uneori, câteva clipe petrecute observând ce este în jur pot aduce puțin mai multă stabilitate și prezență.",
    v1_selectat: true, prioritate: 2, stare_interna: "Ceață", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Orientare; activare nucleu vestibular; ieșire din dorsal",
    surse_teoretice: "Peter Levine; Deb Dana",
    contraindicatii: "Mișcări lente; evitați în probleme cervicale acute, vertij sever",
  },
  {
    id: "M-019", nume: "Apă rece pe față", categorie: "BLOCATĂ", nivel: "SOS",
    energie: "30s", context: ["Acasă"], durata_sec: 20,
    descriere_scurta: "Apă rece pe obraji, frunte și sub ochi. Cincisprezece secunde.",
    trigger_text: "Ai vrea să revii. Dar nu știi cum.",
    pasi: ["Apă rece pe obraji.", "Pe frunte.", "Sub ochi. Cincisprezece secunde."],
    ancora_text: "Șocul blând. Prezența care revine fără să o cauți.",
    inchidere_text: "Atât. Cel mai rapid drum spre acum.",
    v1_selectat: false, prioritate: 1, stare_interna: "Ceață", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Diving reflex; switch parasympathic prin nerv trigeminal",
    surse_teoretice: "Mammalian diving reflex; Peter Levine", contraindicatii: "Raynaud sever",
  },
  {
    id: "M-020", nume: "Trei lucruri, cu un cuvânt fiecare", categorie: "BLOCATĂ", nivel: "SOS",
    energie: "30s", context: ["Acasă", "Birou", "Public", "Mașină"], durata_sec: 20,
    descriere_scurta: "Numești trei lucruri pe care le vezi, cu un adjectiv pentru fiecare.",
    trigger_text: "Mintea ta e undeva departe.",
    pasi: ["Numești în gând trei lucruri pe care le vezi.", "Cu un adjectiv pentru fiecare."],
    ancora_text: "Detaliile care apar când ai cuvinte pentru ele.",
    inchidere_text: "Limbajul te aduce înapoi mai blând decât voința.",
    v1_selectat: true, prioritate: 1, stare_interna: "Ceață", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Labeling; orientare lingvistică; activare prefrontal",
    surse_teoretice: "Deb Dana; Dan Siegel", contraindicatii: "afazie",
  },
  {
    id: "M-021", nume: "Câteva sărituri ușoare", categorie: "BLOCATĂ", nivel: "REGLEAZĂ",
    energie: "30s", context: ["Acasă"], durata_sec: 30,
    descriere_scurta: "Sari ușor pe loc, de pe călcâie, douăzeci de sărituri.",
    trigger_text: "Corpul e greu. Vrei să se trezească.",
    pasi: ["Sari ușor pe loc, doar de pe călcâie.", "Douăzeci de sărituri."],
    ancora_text: "Vibrația care urcă prin oase, până în coloană.",
    inchidere_text: "Oasele transmit vibrația până sus. Întregul corp primește semnalul.",
    v1_selectat: false, prioritate: 2, stare_interna: "Ceață", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Activare scheletică; reset proprioceptiv; ieșire din dorsal",
    surse_teoretice: "Peter Levine", contraindicatii: "leziuni articulații, probleme cardiace",
  },
  {
    id: "M-022", nume: "O singură notă", categorie: "BLOCATĂ", nivel: "REGLEAZĂ",
    energie: "1min", context: ["Acasă", "Mașină"], durata_sec: 45,
    descriere_scurta: "Alegi o notă și o cânți până rămâi fără aer. De trei ori.",
    trigger_text: "Pieptul e gol. Vocea pierdută.",
    pasi: ["Alegi o notă. Una singură.", "O cânți până rămâi fără aer.", "De trei ori."],
    ancora_text: "Vibrația în piept. În gât.",
    inchidere_text: "Vocea e una dintre ușile cele mai directe. Ai redeschis-o.",
    v1_selectat: false, prioritate: 2, stare_interna: "Ceață", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Vagal toning via voce; expir prelungit cu vibrație",
    surse_teoretice: "Stephen Porges; Brown & Gerbarg", contraindicatii: "laringită acută, mutism electiv",
  },
  {
    id: "M-023", nume: "Brațele în jurul umerilor", categorie: "CONECTARE", nivel: "REGLEAZĂ",
    energie: "30s", context: ["Acasă"], durata_sec: 30,
    descriere_scurta: "Brațele încrucișate, mâinile cuprind umerii, strângi ferm treizeci de secunde.",
    trigger_text: "Te simți singur. În propriul corp.",
    pasi: ["Brațele se încrucișează.", "Mâinile cuprind umerii.", "Strângi ferm timp de treizeci de secunde."],
    ancora_text: "Presiunea care spune corpului că e ținut.",
    inchidere_text: "Presiunea profundă liniștește sistemul nervos. Te-ai îmbrățișat ca pe cineva drag.",
    v1_selectat: false, prioritate: 2, stare_interna: "Ceață", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Deep pressure; auto-cuprindere; oxitocina endogenă",
    surse_teoretice: "Deep pressure stimulation; Peter Levine", contraindicatii: "traumă tactilă acută",
  },
  {
    id: "M-024", nume: "Bătăi ușoare, pe rând", categorie: "BLOCATĂ", nivel: "REGLEAZĂ",
    energie: "30s", context: ["Acasă", "Birou", "Mașină"], durata_sec: 30,
    descriere_scurta: "Bați ușor cu palmele pe coapse, pe rând, ritm constant.",
    trigger_text: "Vrei să revii în corp.",
    pasi: ["Bați ușor cu palmele pe coapse, pe rând.", "Ritm constant.", "Treizeci de secunde."],
    ancora_text: "Ritmul. Senzația. Atât.",
    inchidere_text: "Mișcarea ritmică te poate ajuta să te întorci, încet, în prezent. Corpul recunoaște adesea ritmul ca pe un semnal de siguranță.",
    v1_selectat: true, prioritate: 2, stare_interna: "Ceață", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Bilateral stimulation; ritm; reset trauma",
    surse_teoretice: "Principiul stimulării bilaterale; butterfly hug (Jarero & Artigas)",
    contraindicatii: "Alodinie tactilă; nu înlocuiește EMDR clinic",
  },
  {
    id: "M-025", nume: "O gură, cu atenție", categorie: "CONECTARE", nivel: "APROFUNDEAZĂ",
    energie: "1min", context: ["Acasă"], durata_sec: 60,
    descriere_scurta: "O gură de mâncare, mestecată încet, observând gust și textură.",
    trigger_text: "Mănânci dar nu simți.",
    pasi: ["O singură gură.", "O mesteci de douăzeci de ori.", "Observi gust, textură, temperatură."],
    ancora_text: "Gustul real, nu cel din amintire.",
    inchidere_text: "Corpul primește hrană. Tu poți fi prezent pentru acest moment. Începe simplu: o gură, o senzație, un moment de atenție.",
    v1_selectat: false, prioritate: 3, stare_interna: "Ceață", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Mindful eating; interocepție via gust; ventral vagal social",
    surse_teoretice: "Anālayo; Jan Chozen Bays mindful eating", contraindicatii: "TCA activă",
  },
  {
    id: "M-026", nume: "Pragul ușii", categorie: "LINIȘTIRE", nivel: "REGLEAZĂ",
    energie: "30s", context: ["Acasă"], durata_sec: 30,
    descriere_scurta: "Lângă ușă, palmele pe abdomen, respiri, înainte de orice altceva.",
    trigger_text: "Tocmai ai venit acasă.",
    pasi: ["Înainte să faci orice altceva: treizeci de secunde lângă ușă.", "Palmele pe abdomen.", "Respiri."],
    ancora_text: "Lasă-ți atenția să se mute, încet, dinspre afară către aici. Observă cum este să ajungi, cu adevărat, aici.",
    inchidere_text: "Ai marcat o graniță. Sistemul nervos înregistrează asta.",
    v1_selectat: false, prioritate: 2, stare_interna: "Liniștire", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Tranziție conștientă; marker ritual; reglare context",
    surse_teoretice: "BJ Fogg ritualuri; Deb Dana", contraindicatii: "niciuna",
  },
  {
    id: "M-027", nume: "Apă caldă pe mâini", categorie: "LINIȘTIRE", nivel: "REGLEAZĂ",
    energie: "1min", context: ["Acasă"], durata_sec: 60,
    descriere_scurta: "Îți speli mâinile cu apă caldă, foarte încet, un minut.",
    trigger_text: "Tocmai ai avut o discuție grea.",
    pasi: ["Îți speli mâinile cu apă caldă.", "Foarte încet.", "Un minut."],
    ancora_text: "Căldura. Săpunul. Ritualul.",
    inchidere_text: "Apa caldă e un ritual străvechi de tranziție. Corpul știe deja.",
    v1_selectat: true, prioritate: 2, stare_interna: "Liniștire", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Co-reglare cu temperatură; ritual recuperare post-conflict",
    surse_teoretice: "Peter Levine; antropologie rituală", contraindicatii: "leziuni mâini",
  },
  {
    id: "M-028", nume: "Marginea patului", categorie: "LINIȘTIRE", nivel: "REGLEAZĂ",
    energie: "1min", context: ["Acasă", "Pat"], durata_sec: 60,
    descriere_scurta: "Stai pe marginea patului, tălpile pe podea, un minut, fără să faci nimic.",
    trigger_text: "Ziua a fost lungă.",
    pasi: ["Stai pe marginea patului.", "Tălpile pe podea.", "Un minut, fără să faci nimic altceva."],
    ancora_text: "Greutatea corpului care se așază.",
    inchidere_text: "Ziua nu se închide cu o acțiune. Se închide cu o pauză.",
    v1_selectat: true, prioritate: 2, stare_interna: "Liniștire", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Tranziție către somn; oprire conștientă; reset autonom",
    surse_teoretice: "BJ Fogg; sleep research", contraindicatii: "niciuna",
  },
  {
    id: "M-029", nume: "Mâna, blând, pe braț", categorie: "CONECTARE", nivel: "REGLEAZĂ",
    energie: "30s", context: ["Acasă", "Pat"], durata_sec: 30,
    descriere_scurta: "Mângâi ușor brațul de la umăr la încheietură, lent, de cinci ori.",
    trigger_text: "Există o nevoie de apropiere. Și poate începe cu felul în care te întâmpini acum.",
    pasi: ["Mângâi ușor brațul, de la umăr la încheietură.", "Lent.", "De cinci ori."],
    ancora_text: "Senzația pielii care e atinsă cu blândețe.",
    inchidere_text: "Atingerea proprie blândă eliberează oxitocină. E reală.",
    v1_selectat: false, prioritate: 2, stare_interna: "Liniștire", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Atingere C-tactile; oxitocina; auto-compasiune somatică",
    surse_teoretice: "Olausson și colab.; Kristin Neff", contraindicatii: "traumă tactilă",
  },
  {
    id: "M-030", nume: "Un lucru bun, azi", categorie: "CONECTARE", nivel: "APROFUNDEAZĂ",
    energie: "30s", context: ["Acasă", "Birou", "Pat"], durata_sec: 20,
    descriere_scurta: "Numești un singur lucru pe care l-ai făcut bine azi. Mic, banal, real.",
    trigger_text: "La finalul zilei, rămâne impresia că mai trebuia ceva. O zi întreagă, iar vocea critică încă vorbește.",
    pasi: ["Numești un singur lucru pe care l-ai făcut bine astăzi.", "Mic. Banal. Real."],
    ancora_text: "Cum se simte în corp când îl recunoști.",
    inchidere_text: "Nu e despre productivitate. E despre văzut.",
    v1_selectat: true, prioritate: 3, stare_interna: "Liniștire", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Positive recall; recunoaștere de sine; reglare cogniție-corp",
    surse_teoretice: "Rick Hanson; Kristin Neff", contraindicatii: "depresie severă (consultă specialist)",
  },
  {
    id: "M-031", nume: "De ce ai nevoie acum?", categorie: "CONECTARE", nivel: "APROFUNDEAZĂ",
    energie: "30s", context: ["Acasă"], durata_sec: 30,
    descriere_scurta: "Mâna pe piept, întrebi în gând «De ce am nevoie acum?» și aștepți.",
    trigger_text: "Ești obosit. Și nu știi ce ți-ar trebui.",
    pasi: ["Pui mâna pe piept.", "Întrebi, în gând: «De ce ai nevoie acum?»", "Aștepți. Fără să forțezi un răspuns."],
    ancora_text: "Ce vine - un cuvânt, o imagine, o senzație.",
    inchidere_text: "Corpul răspunde când e întrebat cu blândețe. Nu mereu imediat. Dar răspunde.",
    v1_selectat: true, prioritate: 3, stare_interna: "Liniștire", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Focusing (Gendlin); interocepție direcționată; auto-anchetă",
    surse_teoretice: "Eugene Gendlin Focusing; Peter Levine", contraindicatii: "disociere activă",
  },
  {
    id: "M-032", nume: "A fost greu. Am trecut prin asta.", categorie: "OBOSEALĂ", nivel: "APROFUNDEAZĂ",
    energie: "10s", context: ["Acasă", "Birou", "Public"], durata_sec: 15,
    descriere_scurta: "Îți spui: «A fost greu. Am trecut prin asta.»",
    trigger_text: "Tocmai ai terminat ceva greu.",
    pasi: ["Îți spui, cu glas tare sau în gând: «A fost greu. Am trecut prin asta.»"],
    ancora_text: "Diferența între a recunoaște și a sări peste.",
    inchidere_text: "Recunoașterea e cea mai scurtă formă de blândețe cu tine.",
    v1_selectat: true, prioritate: 3, stare_interna: "Liniștire", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Self-validation; integrare experiență; reglare cogniție",
    surse_teoretice: "Marsha Linehan DBT; Kristin Neff", contraindicatii: "niciuna",
  },
  {
    id: "M-033", nume: "O scanare scurtă", categorie: "CONECTARE", nivel: "APROFUNDEAZĂ",
    energie: "30s", context: ["Acasă", "Birou", "Pat"], durata_sec: 30,
    descriere_scurta: "Cu atenția, cobori încet de la creștet la tălpi, doar observând.",
    trigger_text: "Vrei să te asculți. Astăzi.",
    pasi: ["Pornești de la coroană.", "Cobori încet, cu atenția, până la tălpi.", "Treizeci de secunde. Doar observi."],
    ancora_text: "Ce surprinde. Ce e familiar.",
    inchidere_text: "Scanarea e prima formă de prezență.",
    v1_selectat: true, prioritate: 3, stare_interna: "Lumină", ochi_deschisi: null,
    obiectiv_neurofiziologic: "Body scan; interocepție; harta corp",
    surse_teoretice: "Anālayo Satipatthana; MBSR",
    contraindicatii: "disociere - alternativă: scanare doar membre",
  },
  {
    id: "M-034", nume: "Unde respiri cel mai clar?", categorie: "CONECTARE", nivel: "APROFUNDEAZĂ",
    energie: "30s", context: ["Acasă", "Birou"], durata_sec: 20,
    descriere_scurta: "Cauți unde simți respirația cel mai distinct: nări, piept, abdomen?",
    trigger_text: "Curiozitate despre tine.",
    pasi: ["Cauți unde simți respirația cel mai distinct.", "Nările? Pieptul? Abdomenul? Spatele?", "Rămâi acolo o clipă."],
    ancora_text: "Locul tău preferat de respirație, azi.",
    inchidere_text: "Fiecare corp are propria geografie. A ta e a ta. Nu există o hartă universală. Există experiența ta.",
    v1_selectat: false, prioritate: 3, stare_interna: "Lumină", ochi_deschisi: null,
    obiectiv_neurofiziologic: "Anapanasati; localizare respirație; mindfulness specific",
    surse_teoretice: "Anālayo; Anapanasati Sutta", contraindicatii: "anxietate respiratorie activă",
  },
  {
    id: "M-035", nume: "Mâini sau picioare?", categorie: "CONECTARE", nivel: "APROFUNDEAZĂ",
    energie: "30s", context: ["Acasă", "Birou"], durata_sec: 20,
    descriere_scurta: "Compari temperatura mâinilor cu cea a picioarelor, doar observând.",
    trigger_text: "Ai vrea o informație nouă despre tine.",
    pasi: ["Compari temperatura mâinilor cu cea a picioarelor.", "Doar observi diferența."],
    ancora_text: "Datele pe care corpul ți le oferă.",
    inchidere_text: "Termoreglarea spune ceva despre stare. Tu doar ai citit.",
    v1_selectat: false, prioritate: 3, stare_interna: "Lumină", ochi_deschisi: null,
    obiectiv_neurofiziologic: "Interocepție comparativă; awareness termică; date corporale",
    surse_teoretice: "Lisa Feldman Barrett; Antonio Damasio", contraindicatii: "neuropatie periferică",
  },
  {
    id: "M-036", nume: "Unde ții azi tensiunea?", categorie: "CONECTARE", nivel: "APROFUNDEAZĂ",
    energie: "30s", context: ["Acasă", "Birou"], durata_sec: 25,
    descriere_scurta: "Treci prin maxilar, umeri, abdomen, picioare: care e cel mai încordat?",
    trigger_text: "Vrei să știi unde ții azi stresul.",
    pasi: ["Treci prin: maxilar, umeri, abdomen, șezut, picioare.", "Care e cel mai încordat acum?"],
    ancora_text: "Zona care a purtat cel mai mult astăzi.",
    inchidere_text: "Harta tensiunii se schimbă în fiecare zi. Tu doar o citești.",
    v1_selectat: false, prioritate: 3, stare_interna: "Lumină", ochi_deschisi: null,
    obiectiv_neurofiziologic: "Body scan tensional; auto-evaluare; reglare descendentă",
    surse_teoretice: "Peter Levine; Jon Kabat-Zinn MBSR", contraindicatii: "niciuna",
  },
  {
    id: "M-037", nume: "Trei senzații, nu gânduri", categorie: "BLOCATĂ", nivel: "APROFUNDEAZĂ",
    energie: "30s", context: ["Acasă", "Birou", "Public", "Mașină"], durata_sec: 30,
    descriere_scurta: "Numești trei senzații din corp acum. Nu gânduri - senzații.",
    trigger_text: "Vrei un check-in scurt.",
    pasi: ["Numești trei senzații pe care le simți în corp acum.", "Nu emoții - senzații."],
    ancora_text: "Diferența între «sunt obosit» și «simt greutate în pleoape».",
    inchidere_text: "Limbajul senzațiilor e diferit. Și el cere exercițiu.",
    v1_selectat: true, prioritate: 3, stare_interna: "Lumină", ochi_deschisi: null,
    obiectiv_neurofiziologic: "Granularitate senzorială; vocabular interoceptiv; emotion granularity",
    surse_teoretice: "Lisa Feldman Barrett; Antonio Damasio",
    contraindicatii: "alexithymie severă - validează încercarea",
  },
  {
    id: "M-038", nume: "Înainte de telefon", categorie: "LINIȘTIRE", nivel: "SOS",
    energie: "30s", context: ["Acasă", "Pat"], durata_sec: 20,
    descriere_scurta: "Înainte să iei telefonul dimineața: trei respirații. Apoi îl iei.",
    trigger_text: "Te-ai trezit. Mâna se duce spre telefon.",
    pasi: ["Înainte să iei telefonul: trei respirații.", "Atât.", "Apoi poți lua telefonul."],
    ancora_text: "Observă diferența dintre a reacționa și a răspunde. Acesta este momentul în care alegi, nu doar reacționezi.",
    inchidere_text: "Primele trei respirații conștiente setează tonul.",
    v1_selectat: false, prioritate: 1, stare_interna: "Liniștire", ochi_deschisi: null,
    obiectiv_neurofiziologic: "Ritual de dimineață; setare ton circadian; cortisol awareness",
    surse_teoretice: "BJ Fogg; sleep medicine", contraindicatii: "niciuna",
  },
  {
    id: "M-039", nume: "Primele trei înghițituri", categorie: "CONECTARE", nivel: "REGLEAZĂ",
    energie: "1min", context: ["Acasă"], durata_sec: 60,
    descriere_scurta: "Primele trei înghițituri de cafea sau ceai, fără ecran.",
    trigger_text: "Bei prima cafea sau primul ceai.",
    pasi: ["Primele trei înghițituri - fără telefon, fără ecran.", "Doar tu și ceașca."],
    ancora_text: "Căldura. Aroma. Gustul.",
    inchidere_text: "Ai transformat un gest obișnuit într-un moment de prezență. Poate părea mic, dar contează.",
    v1_selectat: false, prioritate: 2, stare_interna: "Lumină", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Mindful drinking; sensory anchoring; ritual matinal",
    surse_teoretice: "Anālayo; BJ Fogg", contraindicatii: "niciuna",
  },
  {
    id: "M-040", nume: "Pragul biroului", categorie: "LINIȘTIRE", nivel: "SOS",
    energie: "30s", context: ["Birou", "Acasă"], durata_sec: 30,
    descriere_scurta: "Înainte de laptop: treizeci de secunde cu ochii închiși, palmele pe abdomen.",
    trigger_text: "Ești pe cale să începi munca.",
    pasi: ["Înainte să deschizi laptopul: treizeci de secunde cu ochii închiși.", "Palmele pe abdomen."],
    ancora_text: "Granița dintre «neînceput» și «început». Primul pas are propriul lui moment.",
    inchidere_text: "Trecerile conștiente schimbă calitatea timpului care urmează.",
    v1_selectat: false, prioritate: 1, stare_interna: "Liniștire", ochi_deschisi: false,
    obiectiv_neurofiziologic: "Tranziție rol; intentional anchoring; pre-task reset",
    surse_teoretice: "BJ Fogg; Cal Newport deep work", contraindicatii: "niciuna",
  },
  {
    id: "M-041", nume: "Două minute înainte de meeting", categorie: "ALERTĂ", nivel: "REGLEAZĂ",
    energie: "1min", context: ["Birou", "Acasă"], durata_sec: 60,
    descriere_scurta: "Tălpile pe podea, maxilarul relaxat, două respirații lungi înainte de meeting.",
    trigger_text: "Următorul meeting începe în două minute.",
    pasi: ["Nu deschizi alt tab. Stai.", "Tălpile pe podea. Maxilarul relaxat.", "Două respirații lungi."],
    ancora_text: "Cum intri în meeting altfel decât ai fi intrat.",
    inchidere_text: "Sistemul nervos se pregătește mai bine cu prezență decât cu informație.",
    v1_selectat: false, prioritate: 2, stare_interna: "Furtună", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Pre-social reglare; ventral activation; reducere anxietate anticipativă",
    surse_teoretice: "Stephen Porges; Deb Dana", contraindicatii: "niciuna",
  },
  {
    id: "M-042", nume: "După laptop, înainte de orice", categorie: "OBOSEALĂ", nivel: "REGLEAZĂ",
    energie: "3min", context: ["Birou", "Acasă"], durata_sec: 90,
    descriere_scurta: "Două minute fără ecran: mers, fereastră sau apă rece pe față.",
    trigger_text: "Ai închis laptop-ul. Sau ai ieșit de la birou.",
    pasi: ["Două minute fără ecran.", "Alegi unul: mers, fereastră, sau apă rece pe față."],
    ancora_text: "De la responsabilități la prezență. Între ceea ce ai oferit și ceea ce ai nevoie acum. Acum te întorci la tine.",
    inchidere_text: "Uneori, sistemul nervos are nevoie de un moment de tranziție. Acum i-l oferi.",
    v1_selectat: false, prioritate: 2, stare_interna: "Liniștire", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Decompresie post-muncă; tranziție rol; marker circadian",
    surse_teoretice: "BJ Fogg; Cal Newport shutdown ritual", contraindicatii: "niciuna",
  },
  {
    id: "M-043", nume: "Pragul somnului", categorie: "LINIȘTIRE", nivel: "REGLEAZĂ",
    energie: "1min", context: ["Acasă", "Pat"], durata_sec: 60,
    descriere_scurta: "Stai pe pat un minut, fără să te întinzi încă. Doar stai și respiri.",
    trigger_text: "Vrei să te culci.",
    pasi: ["Stai pe pat un minut. Nu te întinzi încă.", "Doar stai.", "Respiri."],
    ancora_text: "Încet, corpul se apropie de odihnă. Lasă-te întâmpinat de somn, fără grabă.",
    inchidere_text: "Somnul vine mai ușor când e invitat. Tu doar te-ai oprit la ușa lui.",
    v1_selectat: false, prioritate: 2, stare_interna: "Liniștire", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Sleep onset; ritual seară; melatonin promotion",
    surse_teoretice: "Matthew Walker sleep research", contraindicatii: "insomnia severă - consultă specialist",
  },
  {
    id: "M-044", nume: "Trei respirații înainte să răspunzi", categorie: "ALERTĂ", nivel: "SOS",
    energie: "10s", context: ["Acasă", "Birou", "Public", "Mașină"], durata_sec: 15,
    descriere_scurta: "Trei respirații înainte să răspunzi la un mesaj care te-a tensionat.",
    trigger_text: "Tocmai ai primit un mesaj care te-a tensionat.",
    pasi: ["Trei respirații înainte să răspunzi.", "Doar trei."],
    ancora_text: "Observă diferența dintre a reacționa și a răspunde.",
    inchidere_text: "Spațiul dintre stimul și răspuns e libertate. Trei respirații îl construiesc.",
    v1_selectat: false, prioritate: 1, stare_interna: "Forfotă", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Pause practice; pre-response regulation; agentic choice",
    surse_teoretice: "Viktor Frankl; DBT STOP skill", contraindicatii: "niciuna",
  },
  {
    id: "M-045", nume: "Înainte de o conversație grea", categorie: "ALERTĂ", nivel: "REGLEAZĂ",
    energie: "30s", context: ["Acasă", "Birou", "Public"], durata_sec: 30,
    descriere_scurta: "Tălpile pe podea, simți greutatea, trei respirații înainte să vorbești.",
    trigger_text: "Trebuie să spui ceva dificil.",
    pasi: ["Tălpile pe podea. Simți greutatea.", "Trei respirații adânci."],
    ancora_text: "Faptul că ești susținut de ceva, chiar și în această conversație.",
    inchidere_text: "Pe măsură ce te simți mai prezent în corp, poate deveni mai ușor să spui ceea ce este important.",
    v1_selectat: false, prioritate: 2, stare_interna: "Furtună", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Pre-social reglare; grounding; voice priming",
    surse_teoretice: "Stephen Porges; nonviolent communication", contraindicatii: "niciuna",
  },
  {
    id: "M-046", nume: "După o întâlnire care te-a consumat", categorie: "OBOSEALĂ", nivel: "REGLEAZĂ",
    energie: "1min", context: ["Acasă", "Birou"], durata_sec: 45,
    descriere_scurta: "Speli mâinile sau atingi ceva rece, apoi scuturi ușor din mâini.",
    trigger_text: "Tocmai ai stat cu cineva care te-a consumat.",
    pasi: ["Îți speli mâinile sau atingi ceva rece.", "Treizeci de secunde de scuturat ușor din mâini."],
    ancora_text: "Sentimentul de a lăsa energia celuilalt.",
    inchidere_text: "Granițele se reconstruiesc cu corpul, nu doar cu mintea.",
    v1_selectat: true, prioritate: 2, stare_interna: "Forfotă", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Post-social recovery; energetic boundary; descărcare somatică",
    surse_teoretice: "Peter Levine", contraindicatii: "niciuna",
  },
  {
    id: "M-047", nume: "Înainte să intri în cameră", categorie: "ALERTĂ", nivel: "SOS",
    energie: "30s", context: ["Acasă", "Birou", "Public"], durata_sec: 20,
    descriere_scurta: "Mâna pe stern, trei respirații, apoi intri în încăpere.",
    trigger_text: "Ești pe cale să intri într-o încăpere socială.",
    pasi: ["Mâna pe stern.", "Trei respirații.", "Apoi intri."],
    ancora_text: "Există un loc în tine care rămâne același, indiferent cine este lângă tine.",
    inchidere_text: "Intri în acest spațiu fără să te micșorezi și fără să te adaptezi excesiv.",
    v1_selectat: false, prioritate: 1, stare_interna: "Forfotă", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Self-anchoring social; centering; pre-encounter regulation",
    surse_teoretice: "Stephen Porges; somatic experiencing", contraindicatii: "niciuna",
  },
  {
    id: "M-048", nume: "Privirea panoramică", categorie: "CONECTARE", nivel: "REGLEAZĂ",
    energie: "30s", context: ["Acasă", "Public"], durata_sec: 30,
    descriere_scurta: "Lărgești câmpul vizual și vezi tot ce e la margine, treizeci de secunde.",
    trigger_text: "Ești afară. O secundă.",
    pasi: ["Lărgești câmpul vizual.", "Vezi tot ce e la margine.", "Treizeci de secunde."],
    ancora_text: "Diferența între privirea focusată și cea panoramică.",
    inchidere_text: "Lăsând privirea să se deschidă către întregul spațiu, corpul primește mai multe indicii de siguranță.",
    v1_selectat: false, prioritate: 2, stare_interna: "Lumină", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Panoramic vision; ventral vagal cue; safety signal",
    surse_teoretice: "Andrew Huberman; Stephen Porges", contraindicatii: "niciuna",
  },
  {
    id: "M-049", nume: "Un copac, un minut", categorie: "CONECTARE", nivel: "APROFUNDEAZĂ",
    energie: "1min", context: ["Public", "Acasă"], durata_sec: 60,
    descriere_scurta: "Te oprești lângă un copac, atingi scoarța, privești prin coroană, un minut.",
    trigger_text: "Treci pe lângă un copac.",
    pasi: ["Te oprești.", "Atingi scoarța.", "Privești prin coroană.", "Un minut."],
    ancora_text: "Pentru o clipă, împrumută ritmul unui lucru care crește încet. Copacul nu se grăbește. Observă ce se întâmplă când nici tu nu o faci.",
    inchidere_text: "Uneori, natura ne ajută să ne așezăm fără să spună nimic. Prezența naturii poate schimba ceva subtil în felul în care ne simțim.",
    v1_selectat: false, prioritate: 3, stare_interna: "Lumină", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Forest bathing; co-reglare natură; perspective shift",
    surse_teoretice: "Shinrin-yoku; ecoterapie", contraindicatii: "alergii severe",
  },
  {
    id: "M-050", nume: "Cerul, douăzeci de secunde", categorie: "CONECTARE", nivel: "SOS",
    energie: "30s", context: ["Acasă", "Public"], durata_sec: 20,
    descriere_scurta: "Lasă-ți privirea să se odihnească și privește cerul pentru un moment. Observă cerul așa cum este astăzi.",
    trigger_text: "Te simți închis în tine.",
    pasi: ["Pentru douăzeci de secunde, lasă cerul să fie singurul lucru pe care îl urmărești."],
    ancora_text: "Observă cât spațiu există dincolo de ceea ce privești de obicei.",
    inchidere_text: "Uneori, exteriorul ne amintește că și în interior există mai mult loc decât credeam.",
    v1_selectat: true, prioritate: 1, stare_interna: "Lumină", ochi_deschisi: true,
    obiectiv_neurofiziologic: "Sky gaze; perspective expansion; defocused awareness",
    surse_teoretice: "Andrew Huberman; tradiții contemplative", contraindicatii: "niciuna",
  },
  {
    id: "M-051", nume: "O scânteie", categorie: "CONECTARE", nivel: "APROFUNDEAZĂ",
    energie: "30s", context: ["Acasă", "Birou", "Public"], durata_sec: 30,
    descriere_scurta: "Cauți un singur lucru, oricât de mic, care îți dă un strop de bine acum.",
    trigger_text: "Vrei să observi ce e bine, nu doar ce te apasă.",
    pasi: ["Caută un singur lucru, oricât de mic, care aduce un strop de bine în acest moment.", "Poate fi o culoare. Un sunet. O senzație. O amintire care apare pentru o clipă."],
    ancora_text: "Lasă-ți atenția să observe cum răspunde corpul atunci când recunoști această scânteie.",
    inchidere_text: "Lucrurile mici care fac bine sunt mai dese decât credem. Doar nu le vedem mereu.",
    v1_selectat: true, prioritate: 3, stare_interna: "Lumină", ochi_deschisi: null,
    obiectiv_neurofiziologic: "Positive noticing; ventral activation prin micro-momente; broadening attention",
    surse_teoretice: "Deb Dana; Barbara Fredrickson", contraindicatii: "niciuna",
  },
  {
    id: "M-052", nume: "Legănare cu respirația", categorie: "OBOSEALĂ", nivel: "REGLEAZĂ",
    energie: "1min", context: ["Acasă", "Birou"], durata_sec: 60,
    descriere_scurta: "În picioare, muți greutatea de pe un picior pe altul cu respirația, ca o legănare.",
    trigger_text: "Energia s-a strâns. Nu prea ai unde să o pui.",
    pasi: ["Stai în picioare.", "Greutatea pe un picior la inspir, pe celălalt la expir.", "Foarte ușor, ca o legănare.", "Patru cicluri."],
    ancora_text: "Lasă-ți atenția să urmărească felul în care corpul se sprijină, pe rând, pe fiecare picior.",
    inchidere_text: "Asta e felul corpului de a-și regla singur ritmul. Tu doar îi dai voie.",
    v1_selectat: false, prioritate: 2, stare_interna: "Forfotă", ochi_deschisi: null,
    obiectiv_neurofiziologic: "Vagal brake exercise; coordonare respirație-greutate; reglare ritm autonom",
    surse_teoretice: "Deb Dana; principiul co-reglării prin balans și respirație",
    contraindicatii: "Probleme severe de echilibru, vertij acut",
  },
  {
    id: "M-053", nume: "Șase la inspir, șase la expir", categorie: "ALERTĂ", nivel: "REGLEAZĂ",
    energie: "3min", context: ["Acasă", "Birou", "Public", "Mașină", "Pat"], durata_sec: 90,
    descriere_scurta: "Inspiri pe nas până la șase, expiri până la șase. De cinci ori.",
    trigger_text: "Vrei să cobori, dar pieptul nu se așază.",
    pasi: ["Inspiră ușor pe nas până la șase. Expiră pe nas până la șase. Repetă de cinci ori, fără grabă."],
    ancora_text: "Observă cum inspirul și expirul încep să își găsească același ritm.",
    inchidere_text: "Acest ritm a fost studiat ca optim pentru sistemul nervos. Tu doar îl însoțești.",
    v1_selectat: true, prioritate: 2, stare_interna: "Furtună", ochi_deschisi: null,
    obiectiv_neurofiziologic: "Coherent breathing (~5 breaths/min); maximizare HRV; sympathovagal balance",
    surse_teoretice: "Brown & Gerbarg; cercetare HRV",
    contraindicatii: "Evitați în panică acută cu hiperventilație",
  },
  {
    id: "M-054", nume: "Un singur cuvânt", categorie: "BLOCATĂ", nivel: "APROFUNDEAZĂ",
    energie: "30s", context: ["Acasă", "Birou", "Public", "Mașină"], durata_sec: 25,
    descriere_scurta: "Caută un singur cuvânt pentru ce se petrece în tine acum.",
    trigger_text: "Simți ceva, dar nu știi exact ce.",
    pasi: ["Caută un cuvânt - unul singur - pentru ce se petrece în tine.", "Nu trebuie să fie perfect. Doar cel mai apropiat."],
    ancora_text: "Observă dacă starea rămâne la fel sau începe să se transforme ușor după ce îi dai un nume.",
    inchidere_text: "Cuvântul nu rezolvă, dar așază. Asta e suficient.",
    v1_selectat: true, prioritate: 3, stare_interna: "Ceață", ochi_deschisi: null,
    obiectiv_neurofiziologic: "Affect labeling; reducere activare amigdala via verbalizare; granularitate emoțională",
    surse_teoretice: "Matthew Lieberman; Lisa Feldman Barrett",
    contraindicatii: "Alexithymie severă - validează încercarea ca succes",
  },
  {
    id: "M-055", nume: "Un pas mic înainte", categorie: "ALERTĂ", nivel: "APROFUNDEAZĂ",
    energie: "30s", context: ["Acasă", "Birou", "Public"], durata_sec: 30,
    descriere_scurta: "Lași decizia mare; cauți doar cel mai mic pas adevărat pentru următorul minut.",
    trigger_text: "Te simți blocat între două direcții și nu reușești să faci niciun pas.",
    pasi: ["Lasă întrebările mari să aștepte puțin.", "Adu-ți atenția către pasul cel mai mic și mai adevărat care este posibil acum.", "Atât de mic încât corpul nu se sperie de el."],
    ancora_text: "Cum se simte corpul când o singură mișcare devine clară.",
    inchidere_text: "Nu toată povestea. Doar următorul pas. Uneori, atât este suficient.",
    v1_selectat: true, prioritate: 3, stare_interna: "Furtună", ochi_deschisi: null,
    obiectiv_neurofiziologic: "Reducerea încărcăturii decizionale + activare comportamentală",
    surse_teoretice: "Activare comportamentală (Lewinsohn, Jacobson); principiul pauzei (Frankl / DBT STOP)",
    contraindicatii: "Niciuna",
  },
];
