// ─── Mock Data for all pages ───────────────────────────────────────────────

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Maria D.",
    city: "București",
    stars: 5,
    quote: "WithIn mi-a schimbat radical modul în care gestionez anxietatea. Exercițiile sunt scurte, dar extrem de puternice.",
    weeks: 6,
    topics: ["Anxietate", "Respirație"],
  },
  {
    id: 2,
    name: "Andrei T.",
    city: "Cluj-Napoca",
    stars: 5,
    quote: "Simt o conexiune mult mai profundă cu propriul corp. Este refugiul meu zilnic în mijlocul haosului.",
    weeks: 12,
    topics: ["Stres", "Somn"],
  },
  {
    id: 3,
    name: "Elena R.",
    city: "Timișoara",
    stars: 5,
    quote: "Practicile de reglare somatică m-au ajutat să ies din starea de burnout. Recoman cu căldură fiecărei persoane.",
    weeks: 8,
    topics: ["Burnout", "Energie"],
  },
  {
    id: 4,
    name: "Cristina M.",
    city: "Iași",
    stars: 5,
    quote: "Somnul meu s-a îmbunătățit dramatic după doar 2 săptămâni. Nu mă mai trezesc de 5 ori pe noapte.",
    weeks: 4,
    topics: ["Somn", "Relaxare"],
  },
  {
    id: 5,
    name: "Radu P.",
    city: "Brașov",
    stars: 5,
    quote: "Ca bărbat, eram sceptic față de 'terapia somatică'. Acum nu pot imagina ziua fără practica de dimineață.",
    weeks: 10,
    topics: ["Reglare", "Claritate"],
  },
  {
    id: 6,
    name: "Ioana V.",
    city: "Constanța",
    stars: 5,
    quote: "Facilitatoarea mea, Dr. Ana, este extraordinară. Sesiunile live sunt un moment de respiro autentic.",
    weeks: 16,
    topics: ["Sesiuni live", "Corp"],
  },
];

export const FACILITATORS = [
  {
    id: 1,
    slug: "ana-ionescu",
    name: "Dr. Ana Ionescu",
    title: "Terapeut Somatic Certificat",
    tags: ["Traumă", "Anxietate", "Burnout"],
    rating: 4.9,
    reviews: 142,
    bio: "Specialist în terapia somatică și reglarea sistemului nervos, cu peste 12 ani de experiență. Formată în SEA (Somatic Experiencing) și EMDR.",
    photo: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80",
    practiceDuration: "12 ani",
    specialties: ["Traumă", "Anxietate", "Burnout", "Reglare somatică"],
    certifications: ["Somatic Experiencing (SEA)", "EMDR Level 2", "Mindfulness-Based Stress Reduction"],
  },
  {
    id: 2,
    slug: "mihai-pop",
    name: "Mihai Pop",
    title: "Practician Somatic & Yoga",
    tags: ["Somn", "Energie", "Mișcare"],
    rating: 4.8,
    reviews: 98,
    bio: "Specialist în practicile de corp-minte, yoga terapeutică și somatic movement. Ajută oamenii să redescopere bucuria de a fi în propriul corp.",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    practiceDuration: "8 ani",
    specialties: ["Somn", "Energie", "Mișcare", "Yoga"],
    certifications: ["Yoga Alliance RYT-500", "Somatic Movement Education"],
  },
  {
    id: 3,
    slug: "elena-stan",
    name: "Elena Stan",
    title: "Psihoterapeut & Coach Somatic",
    tags: ["Relații", "Limite", "Reglare"],
    rating: 4.9,
    reviews: 203,
    bio: "Psihoterapeut integrativ cu specializare în terapia somatică a traumei relaționale. Creator al programului 'Corp și Limite'.",
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80",
    practiceDuration: "15 ani",
    specialties: ["Relații", "Limite", "Trauma relațională", "Reglare"],
    certifications: ["Psihoterapie Integrativă", "Bodynamic", "NeuroAffective Touch"],
  },
  {
    id: 4,
    slug: "cristian-dima",
    name: "Cristian Dima",
    title: "Specialist Respirație & Sunet",
    tags: ["Respirație", "Voce", "Stres"],
    rating: 4.7,
    reviews: 67,
    bio: "Expert în tehnicile de respirație terapeutică și terapia prin sunet. Combină practicile antice cu neuroștiința modernă.",
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80",
    practiceDuration: "6 ani",
    specialties: ["Respirație", "Voce", "Reducerea stresului", "Meditație"],
    certifications: ["Holotropic Breathwork", "Sound Healing Practitioner"],
  },
];

export const PRACTICES = [
  {
    id: 1,
    title: "Respirație 4-7-8 pentru anxietate",
    category: "Suflu",
    facilitator: "Dr. Ana Ionescu",
    facilitatorSlug: "ana-ionescu",
    duration: 10,
    level: "Începător",
    isPremium: false,
    mediaType: "audio",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4",
    thumbnail: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4",
    description: "O tehnică clasică de respirație care activează sistemul nervos parasimpatic în câteva minute.",
    longDescription: "Descriere în curând.",
    tags: ["Anxietate", "Relaxare", "Respirație"],
  },
  {
    id: 2,
    title: "Scanarea corpului — eliberare tensiune",
    category: "Prezență",
    facilitator: "Elena Stan",
    facilitatorSlug: "elena-stan",
    duration: 20,
    level: "Începător",
    isPremium: false,
    mediaType: "audio",
    image: "https://images.unsplash.com/photo-1545389336-cf090694435e",
    thumbnail: "https://images.unsplash.com/photo-1545389336-cf090694435e",
    description: "Călătorie ghidată prin fiecare parte a corpului pentru a identifica și elibera tensiunile acumulate.",
    longDescription: "Descriere în curând.",
    tags: ["Corp", "Relaxare", "Tensiune"],
  },
  {
    id: 3,
    title: "Shaking — descărcare somatică",
    category: "Fluiditate",
    facilitator: "Mihai Pop",
    facilitatorSlug: "mihai-pop",
    duration: 15,
    level: "Intermediar",
    isPremium: true,
    mediaType: "video",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b",
    thumbnail: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b",
    description: "Practică TRE (Tension & Trauma Releasing Exercises) pentru descărcarea tensiunilor profunde din corp.",
    longDescription: "Descriere în curând.",
    tags: ["Mișcare", "Traumă", "Descărcare"],
  },
  {
    id: 4,
    title: "Ritual de adormire — glanda pineală",
    category: "Odihnă",
    facilitator: "Mihai Pop",
    facilitatorSlug: "mihai-pop",
    duration: 20,
    level: "Începător",
    isPremium: false,
    mediaType: "audio",
    image: "https://images.unsplash.com/photo-1531353826977-0941b4779a1c",
    thumbnail: "https://images.unsplash.com/photo-1531353826977-0941b4779a1c",
    description: "Secvență de relaxare progresivă și vizualizare pentru a intra ușor în somn profund.",
    longDescription: "Descriere în curând.",
    tags: ["Somn", "Relaxare", "Vizualizare"],
  },
  {
    id: 5,
    title: "Activare dimineață — energie vitală",
    category: "Vitalitate",
    facilitator: "Cristian Dima",
    facilitatorSlug: "cristian-dima",
    duration: 10,
    level: "Începător",
    isPremium: false,
    mediaType: "video",
    image: "https://images.unsplash.com/photo-1508672019048-805c876b67e2",
    thumbnail: "https://images.unsplash.com/photo-1508672019048-805c876b67e2",
    description: "Combinație de respirație energizantă și mișcări ușoare pentru a porni ziua cu claritate.",
    longDescription: "Descriere în curând.",
    tags: ["Energie", "Dimineață", "Claritate"],
  },
  {
    id: 6,
    title: "Vocalizare somatică — vocea corpului",
    category: "Expresie",
    facilitator: "Cristian Dima",
    facilitatorSlug: "cristian-dima",
    duration: 25,
    level: "Intermediar",
    isPremium: true,
    mediaType: "audio",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745",
    thumbnail: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745",
    description: "Explorare ghidată a rezonanțelor vocale pentru eliberarea emoțională și reconectare.",
    longDescription: "Descriere în curând.",
    tags: ["Voce", "Emoții", "Eliberare"],
  },
  {
    id: 7,
    title: "Ancorare în prezent — tehnica 5-4-3-2-1",
    category: "Suflu",
    facilitator: "Dr. Ana Ionescu",
    facilitatorSlug: "ana-ionescu",
    duration: 5,
    level: "Începător",
    isPremium: false,
    mediaType: "audio",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e",
    thumbnail: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e",
    description: "Tehnică rapidă de grounding senzorial pentru momentele de anxietate sau disociere.",
    longDescription: "Descriere în curând.",
    tags: ["Anxietate", "Grounding", "Prezent"],
  },
  {
    id: 8,
    title: "Mișcare expresivă — fluxul liber",
    category: "Fluiditate",
    facilitator: "Elena Stan",
    facilitatorSlug: "elena-stan",
    duration: 30,
    level: "Avansat",
    isPremium: true,
    mediaType: "video",
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a",
    thumbnail: "https://images.unsplash.com/photo-1518611012118-696072aa579a",
    description: "Practică de mișcare autentică pentru eliberarea emoțiilor blocate și reconectare cu bucuria.",
    longDescription: "Descriere în curând.",
    tags: ["Mișcare", "Emoții", "Bucurie"],
  },
  {
    id: 9,
    title: "NSDR — repaus profund non-somn",
    category: "Odihnă",
    facilitator: "Mihai Pop",
    facilitatorSlug: "mihai-pop",
    duration: 20,
    level: "Începător",
    isPremium: true,
    mediaType: "audio",
    image: "https://images.unsplash.com/photo-1440716659370-f09c5ee55753",
    thumbnail: "https://images.unsplash.com/photo-1440716659370-f09c5ee55753",
    description: "Protocol de recuperare rapidă care restaurează energia mentală în 20 de minute.",
    longDescription: "Descriere în curând.",
    tags: ["Somn", "Recuperare", "NSDR"],
  },
];

// Datele demo sunt generate relativ la ziua curentă, ca sesiunile să fie mereu în viitor
function upcomingDate(daysAhead: number, hour: number, minute = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + daysAhead);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function minutesFromNow(minutes: number): string {
  return new Date(Date.now() + minutes * 60 * 1000).toISOString();
}

export const LIVE_SESSIONS = [
  {
    id: 1,
    title: "Reglare somatică de grup — reducerea stresului",
    facilitator: "Dr. Ana Ionescu",
    date: minutesFromNow(120), // peste 2 ore — anularea e permisă (test)
    duration: 60,
    spotsTotal: 25,
    spotsLeft: 8,
    type: "Grup",
    isPremium: false,
    zoomLink: "#",
    description: "Sesiune de grup ghidată pentru reglarea sistemului nervos prin practici somatice.",
  },
  {
    id: 2,
    title: "Yoga somatică — dimineața corpului",
    facilitator: "Mihai Pop",
    date: upcomingDate(2, 7, 30),
    duration: 45,
    spotsTotal: 20,
    spotsLeft: 12,
    type: "Grup",
    isPremium: true,
    zoomLink: "#",
    description: "Practică de dimineață combinând yoga terapeutică cu elemente de somatic awareness.",
  },
  {
    id: 3,
    title: "Q&A — Trauma și corpul (live)",
    facilitator: "Elena Stan",
    date: minutesFromNow(10), // peste 10 min — în fereastra de 20 min, anularea e blocată (test)
    duration: 90,
    spotsTotal: 50,
    spotsLeft: 23,
    type: "Q&A",
    isPremium: false,
    zoomLink: "#",
    description: "Sesiune de întrebări și răspunsuri despre trauma stocată în corp și procesele de vindecare.",
  },
  {
    id: 4,
    title: "Respirație holotropică — eliberare profundă",
    facilitator: "Cristian Dima",
    date: upcomingDate(5, 15, 0),
    duration: 120,
    spotsTotal: 15,
    spotsLeft: 3,
    type: "Intensiv",
    isPremium: true,
    zoomLink: "#",
    description: "Sesiune intensivă de respirație holotropică în grup mic, pentru experiențe profunde de eliberare.",
  },
];

export const PAST_RECORDINGS = [
  {
    id: 1,
    title: "Introducere în terapia somatică",
    facilitator: "Dr. Ana Ionescu",
    date: "2026-04-20",
    duration: 60,
    views: 342,
    isPremium: false,
    thumbnail: "/images/rec-1.jpg",
  },
  {
    id: 2,
    title: "Gestionarea anxietății prin corp",
    facilitator: "Elena Stan",
    date: "2026-04-15",
    duration: 75,
    views: 287,
    isPremium: true,
    thumbnail: "/images/rec-2.jpg",
  },
  {
    id: 3,
    title: "Tehnici de grounding pentru momentele dificile",
    facilitator: "Cristian Dima",
    date: "2026-04-10",
    duration: 45,
    views: 198,
    isPremium: false,
    thumbnail: "/images/rec-3.jpg",
  },
];

export const BLOG_POSTS = [
  {
    id: 1,
    slug: "ce-este-terapia-somatica",
    title: "Ce este terapia somatică și cum te poate ajuta",
    category: "Educație",
    author: "Dr. Ana Ionescu",
    authorRole: "Terapeut Somatic",
    date: "2026-04-28",
    readTime: 8,
    excerpt: "Terapia somatică este o abordare holistică care recunoaște legătura profundă dintre minte și corp. Spre deosebire de terapia tradițională...",
    image: "/images/blog-1.jpg",
    isFeatured: true,
    tags: ["Somatic", "Educație", "Terapie"],
  },
  {
    id: 2,
    slug: "5-practici-pentru-anxietate",
    title: "5 practici somatice pentru anxietate pe care le poți face azi",
    category: "Practici",
    author: "Elena Stan",
    authorRole: "Psihoterapeut",
    date: "2026-04-22",
    readTime: 6,
    excerpt: "Anxietatea este stocată în corp, nu doar în minte. Iată 5 tehnici somatice pe care le poți folosi chiar acum...",
    image: "/images/blog-2.jpg",
    isFeatured: false,
    tags: ["Anxietate", "Practici", "Corp"],
  },
  {
    id: 3,
    slug: "trauma-si-sistemul-nervos",
    title: "Trauma și sistemul nervos: ce se întâmplă de fapt în corp",
    category: "Știință",
    author: "Dr. Ana Ionescu",
    authorRole: "Terapeut Somatic",
    date: "2026-04-15",
    readTime: 12,
    excerpt: "Cercetările lui Peter Levine și Bessel van der Kolk au revoluționat înțelegerea noastră despre traumă...",
    image: "/images/blog-3.jpg",
    isFeatured: false,
    tags: ["Traumă", "Știință", "Sistem nervos"],
  },
  {
    id: 4,
    slug: "respiratia-si-vagul",
    title: "Respirația și nervul vag: poarta ta spre calm",
    category: "Știință",
    author: "Cristian Dima",
    authorRole: "Specialist Respirație",
    date: "2026-04-08",
    readTime: 7,
    excerpt: "Nervul vag este cea mai lungă cale nervoasă din corpul tău. Prin respirație, poți activa direct tonusul vagal...",
    image: "/images/blog-4.jpg",
    isFeatured: false,
    tags: ["Respirație", "Nervul vag", "Știință"],
  },
  {
    id: 5,
    slug: "burnout-somatic",
    title: "Burnout somatic: când corpul tău spune 'stop'",
    category: "Resurse",
    author: "Elena Stan",
    authorRole: "Psihoterapeut",
    date: "2026-04-01",
    readTime: 9,
    excerpt: "Burnout-ul nu este doar oboseală. Este o deconectare profundă de la propriul sistem de semnalizare corporal...",
    image: "/images/blog-5.jpg",
    isFeatured: false,
    tags: ["Burnout", "Resurse", "Corp"],
  },
  {
    id: 6,
    slug: "somn-si-sistemul-nervos",
    title: "De ce somnul este terapie somatică",
    category: "Odihnă",
    author: "Mihai Pop",
    authorRole: "Practician Somatic",
    date: "2026-03-25",
    readTime: 5,
    excerpt: "Somnul profund este momentul în care corpul procesează și integrează experiențele emoționale din zi...",
    image: "/images/blog-6.jpg",
    isFeatured: false,
    tags: ["Somn", "Recuperare", "Corp"],
  },
];

export const PRICING_PLANS = [
  {
    id: "gratuit",
    name: "Gratuit",
    price: 0,
    priceAnnual: 0,
    description: "Recalibrare rapidă",
    color: "#3A6850",
    features: [
      "5 practici gratuite pe lună",
      "1 sesiune live pe lună",
      "Check-in zilnic",
      "Acces la blog și resurse",
      "Monitorizarea progresului",
    ],
    notIncluded: [
      "Bibliotecă completă (70+ practici)",
      "Sesiuni live nelimitate",
      "Progres personalizat",
      "Suport dedicat",
    ],
    cta: "Începe gratuit",
    isPopular: false,
  },
  {
    id: "premium",
    name: "Standard",
    price: 59,
    priceAnnual: 39,
    description: "Claritate și echilibru",
    color: "#2B8C5C",
    features: [
      "Acces nelimitat la toate practicile",
      "Sesiuni live nelimitate",
      "Check-in zilnic + harta corpului",
      "Progres personalizat",
      "Monitorizarea progresului",
      "Recomandări bazate pe check-in",
      "Suport email 48h",
    ],
    notIncluded: ["Sesiuni 1:1 cu facilitatorul", "Program corporativ"],
    cta: "Începe Premium",
    isPopular: true,
  },
  {
    id: "premium-plus",
    name: "Premium",
    price: 89,
    priceAnnual: 59,
    description: "Transformare profundă",
    color: "#0F2E1A",
    features: [
      "Tot ce include Premium",
      "1 sesiune 1:1 pe lună cu facilitatorul",
      "Program personalizat de 30 zile",
      "Acces anticipat la conținut nou",
      "Grup privat de suport",
      "Suport prioritar 24h",
      "Download practici offline",
    ],
    notIncluded: [],
    cta: "Începe Premium+",
    isPopular: false,
  },
];

export const FAQ_ITEMS = [
  {
    q: "Ce este terapia somatică și cu ce diferă de meditație?",
    a: "Terapia somatică se concentrează pe senzațiile corporale și cum acestea poartă amprenta experiențelor noastre emoționale și traumatice. Spre deosebire de meditație (care lucrează cu mintea), terapia somatică lucrează direct cu corpul ca 'intrare' în sistemul nervos.",
  },
  {
    q: "Am nevoie de experiență anterioară?",
    a: "Nu. Platforma este concepută pentru toate nivelurile, de la absolute beginner la practicieni cu experiență. Fiecare sesiune indică nivelul recomandat.",
  },
  {
    q: "Cât timp durează o practică?",
    a: "Practicile variază de la 5 minute (tehnici rapide de ancorare) la 30+ minute (sesiuni profunde de corp). Majoritatea utilizatorilor practică 10-20 de minute pe zi.",
  },
  {
    q: "Poate înlocui WithIn terapia clasică?",
    a: "WithIn este un instrument de suport, nu un substitut pentru psihoterapie. Dacă ai nevoie de suport terapeutic individual, te încurajăm să lucrezi și cu un terapeut calificat.",
  },
  {
    q: "Cum funcționează perioada gratuită de 14 zile?",
    a: "Primele 14 zile sunt complet gratuite și îți oferă acces la planul Premium pentru a testa experiența. Planul Premium Plus nu este inclus în perioada de probă. Nu ai nevoie de card pentru a începe.",
  },
  {
    q: "Pot descărca practicile pentru utilizare offline?",
    a: "Descărcarea offline este disponibilă pentru abonații Premium+. Planurile Gratuit și Premium necesită conexiune internet.",
  },
  {
    q: "Sesiunile live sunt înregistrate?",
    a: "Da, toate sesiunile live sunt înregistrate și disponibile în biblioteca de replay în termen de 24 de ore. Abonații Premium și Premium+ au acces la arhiva completă.",
  },
  {
    q: "Există opțiuni corporate / B2B?",
    a: "Da! Oferim pachete corporate pentru companii care doresc să investească în bunăstarea angajaților. Contactați-ne la business@inauntru.ro pentru un demo și ofertă personalizată.",
  },
];

export const INTENT_CARDS = [
  {
    id: "liniste",
    icon: "Leaf",
    title: "Pauză de reîncărcare",
    desc: "Eliberează tensiunea acumulată",
    color: "bg-light-green border-sage-border",
  },
  {
    id: "somn",
    icon: "Moon",
    title: "Somn odihnitor",
    desc: "Pregătește corpul pentru odihnă",
    color: "bg-surface-container border-outline-variant",
  },
  {
    id: "anxietate",
    icon: "Wind",
    title: "Eliberare de presiune și agitație",
    desc: "Ancorează-te în prezent",
    color: "bg-surface-container border-outline-variant",
  },
  {
    id: "energie",
    icon: "Sun",
    title: "Prezență și claritate mentală",
    desc: "Activează vitalitatea",
    color: "bg-surface-container border-outline-variant",
  },
  {
    id: "reglare",
    icon: "Heartbeat",
    title: "Recalibrare și echilibru interior",
    desc: "Echilibrează sistemul nervos",
    color: "bg-surface-container border-outline-variant",
  },
  {
    id: "explorare",
    icon: "Sparkle",
    title: "Explorare și creștere",
    desc: "Adâncește conexiunea cu tine",
    color: "bg-surface-container border-outline-variant",
  },
];

export type UserRole = "user" | "facilitator" | "moderator" | "editor" | "super_admin";

export type AdminUser = {
  id: number;
  name: string;
  email: string;
  plan: string;
  joinDate: string;
  lastActive: string;
  checkIns: number;
  avatar: string;
  role: UserRole;
  facilitatorProfile?: {
    title: string;
    bio: string;
    specialties: string[];
    photo: string;
  };
};

export const ADMIN_USERS: AdminUser[] = [
  { id: 1, name: "Maria Dumitrescu", email: "maria.d@gmail.com", plan: "Premium+", joinDate: "2026-01-15", lastActive: "2026-04-30", checkIns: 47, avatar: "MD", role: "user" },
  { id: 2, name: "Andrei Toma", email: "andrei.t@gmail.com", plan: "Premium", joinDate: "2026-02-03", lastActive: "2026-04-29", checkIns: 31, avatar: "AT", role: "user" },
  { id: 3, name: "Elena Radu", email: "elena.r@yahoo.ro", plan: "Gratuit", joinDate: "2026-03-20", lastActive: "2026-04-28", checkIns: 12, avatar: "ER", role: "user" },
  { id: 4, name: "Cristina Mihai", email: "cristina.m@gmail.com", plan: "Premium", joinDate: "2026-01-28", lastActive: "2026-04-30", checkIns: 63, avatar: "CM", role: "user" },
  { id: 5, name: "Radu Popescu", email: "radu.p@gmail.com", plan: "Premium+", joinDate: "2025-12-10", lastActive: "2026-04-30", checkIns: 89, avatar: "RP", role: "user" },
  { id: 6, name: "Ioana Vasile", email: "ioana.v@gmail.com", plan: "Gratuit", joinDate: "2026-04-01", lastActive: "2026-04-25", checkIns: 8, avatar: "IV", role: "user" },
  { id: 7, name: "Tudor Ionescu", email: "tudor.i@gmail.com", plan: "Premium", joinDate: "2026-02-14", lastActive: "2026-04-30", checkIns: 44, avatar: "TI", role: "moderator" },
  { id: 8, name: "Ana Constantin", email: "ana.c@yahoo.ro", plan: "Premium+", joinDate: "2026-01-05", lastActive: "2026-04-29", checkIns: 102, avatar: "AC", role: "user" },
];

export const ADMIN_CONTENT = [
  { id: 1, title: "Respirație 4-7-8 pentru anxietate", category: "Suflu", facilitator: "Dr. Ana Ionescu", status: "active", views: 1247, rating: 4.9 },
  { id: 2, title: "Scanarea corpului — eliberare tensiune", category: "Prezență", facilitator: "Elena Stan", status: "active", views: 983, rating: 4.8 },
  { id: 3, title: "Shaking — descărcare somatică", category: "Fluiditate", facilitator: "Mihai Pop", status: "active", views: 756, rating: 4.7 },
  { id: 4, title: "Ritual de adormire — glanda pineală", category: "Odihnă", facilitator: "Mihai Pop", status: "active", views: 1104, rating: 4.9 },
  { id: 5, title: "Activare dimineață — energie vitală", category: "Vitalitate", facilitator: "Cristian Dima", status: "active", views: 892, rating: 4.6 },
  { id: 6, title: "Vocalizare somatică — vocea corpului", category: "Expresie", facilitator: "Cristian Dima", status: "draft", views: 0, rating: 0 },
  { id: 7, title: "Ancorare în prezent — 5-4-3-2-1", category: "Suflu", facilitator: "Dr. Ana Ionescu", status: "active", views: 2134, rating: 4.9 },
  { id: 8, title: "Mișcare expresivă — fluxul liber", category: "Fluiditate", facilitator: "Elena Stan", status: "draft", views: 0, rating: 0 },
];

export const REVENUE_DATA = [
  { date: "1 Apr", revenue: 12400, subscribers: 4 },
  { date: "5 Apr", revenue: 13100, subscribers: 7 },
  { date: "10 Apr", revenue: 14200, subscribers: 12 },
  { date: "15 Apr", revenue: 15300, subscribers: 9 },
  { date: "20 Apr", revenue: 16100, subscribers: 15 },
  { date: "25 Apr", revenue: 17200, subscribers: 11 },
  { date: "30 Apr", revenue: 18408, subscribers: 18 },
];

export const HOURLY_VIEWS = [
  { hour: "6", views: 12 },
  { hour: "7", views: 45 },
  { hour: "8", views: 89 },
  { hour: "9", views: 67 },
  { hour: "10", views: 43 },
  { hour: "11", views: 38 },
  { hour: "12", views: 52 },
  { hour: "13", views: 48 },
  { hour: "14", views: 35 },
  { hour: "15", views: 41 },
  { hour: "16", views: 56 },
  { hour: "17", views: 78 },
  { hour: "18", views: 134 },
  { hour: "19", views: 168 },
  { hour: "20", views: 147 },
  { hour: "21", views: 112 },
  { hour: "22", views: 76 },
  { hour: "23", views: 34 },
];

export const FUNNEL_DATA = [
  { step: "Vizitatori", value: 45230, pct: 100 },
  { step: "Înregistrați", value: 8940, pct: 19.8 },
  { step: "Trial început", value: 3120, pct: 6.9 },
  { step: "Plată efectuată", value: 1547, pct: 3.4 },
];
