import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Core brand — Verde Intermediar + Indigo
        "forest-green": "#2B8C5C",
        "deep-green": "#0F2E1A",
        "light-green": "#E6F5ED",
        "sage-border": "#A8DFC0",
        "bg-main": "#F2F2FF",
        "secondary-text": "#3A6850",
        "rose-powder": "#EAEBFF",
        "terracotta": "#3D3FAA",
        // Indigo accent system
        "indigo": "#3D3FAA",
        "indigo-dark": "#252680",
        "indigo-mid": "#6668CC",
        "indigo-light": "#EAEBFF",
        "indigo-bg": "#E8E8F8",
        "nav-bg": "#F2F2FF",
        "nav-border": "#C8C8F0",
        // Verde mid
        "verde-mid": "#4AAA78",
        // Material tokens
        "primary": "#2B8C5C",
        "primary-dark": "#0F2E1A",
        "primary-container": "#2B8C5C",
        "on-primary": "#ffffff",
        "on-primary-container": "#E6F5ED",
        "primary-fixed": "#A8DFC0",
        "primary-fixed-dim": "#8ACCA8",
        "inverse-primary": "#8ACCA8",
        "secondary": "#3D3FAA",
        "on-secondary": "#ffffff",
        "secondary-container": "#EAEBFF",
        "on-secondary-container": "#252680",
        "secondary-fixed": "#EAEBFF",
        "secondary-fixed-dim": "#C8C8F0",
        "tertiary": "#6668CC",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#3D3FAA",
        "on-tertiary-container": "#EAEBFF",
        "tertiary-fixed": "#EAEBFF",
        "tertiary-fixed-dim": "#3D3FAA",
        "surface": "#F2F2FF",
        "surface-dim": "#A8DFC0",
        "surface-bright": "#F2F2FF",
        "surface-variant": "#E8E8F8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#E6F5ED",
        "surface-container": "#E6F5ED",
        "surface-container-high": "#E8E8F8",
        "surface-container-highest": "#A8DFC0",
        "on-surface": "#0F2E1A",
        "on-surface-variant": "#3A6850",
        "surface-tint": "#2B8C5C",
        "background": "#F2F2FF",
        "on-background": "#0F2E1A",
        "outline": "#3A6850",
        "outline-variant": "#A8DFC0",
        "inverse-surface": "#0F2E1A",
        "inverse-on-surface": "#E6F5ED",
        "error": "#3D3FAA",
        "on-error": "#ffffff",
        "error-container": "#EAEBFF",
        "on-error-container": "#252680",
      },
      fontFamily: {
        heading: ["var(--font-heading)", "Georgia", "serif"],
        body: ["var(--font-body)", "system-ui", "sans-serif"],
        ui: ["var(--font-body)", "system-ui", "sans-serif"],
        serif: ["var(--font-heading)", "Georgia", "serif"],
        sans: ["var(--font-body)", "system-ui", "sans-serif"],
      },
      fontSize: {
        display: ["56px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        h1: ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        h2: ["36px", { lineHeight: "1.3", fontWeight: "600" }],
        h3: ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        h4: ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-xs": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        "2xl": "32px",
        full: "9999px",
        card: "16px",
        button: "99px",
      },
      spacing: {
        xs: "8px",
        sm: "16px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        gutter: "24px",
      },
      boxShadow: {
        card: "0 0 0 1px rgba(15, 46, 26, 0.05), 0 2px 12px rgba(15, 46, 26, 0.06)",
        "card-hover": "0 0 0 1px rgba(15, 46, 26, 0.08), 0 6px 24px rgba(15, 46, 26, 0.10)",
        nav: "0 1px 8px rgba(61, 63, 170, 0.08)",
        modal: "0 8px 48px rgba(15, 46, 26, 0.18)",
        button: "0 2px 8px rgba(43, 140, 92, 0.28)",
      },
      keyframes: {
        breathe: {
          "0%, 100%": { transform: "scale(1)", opacity: "0.6" },
          "50%": { transform: "scale(1.08)", opacity: "0.9" },
        },
        "slide-up": {
          "0%": { transform: "translateY(100%)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "slide-down": {
          "0%": { transform: "translateY(-60px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "fade-up": {
          "0%": { transform: "translateY(30px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "skeleton-pulse": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        ripple: {
          "0%": { transform: "scale(0)", opacity: "0.4" },
          "100%": { transform: "scale(2.5)", opacity: "0" },
        },
        "live-pulse": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.5", transform: "scale(0.8)" },
        },
      },
      animation: {
        breathe: "breathe 4s ease-in-out infinite",
        "breathe-slow": "breathe 8s ease-in-out infinite",
        "slide-up": "slide-up 0.4s ease-out",
        "slide-down": "slide-down 0.5s ease-out",
        "fade-up": "fade-up 0.7s ease-out",
        "skeleton-pulse": "skeleton-pulse 1.5s ease-in-out infinite",
        ripple: "ripple 0.6s ease-out",
        "live-pulse": "live-pulse 2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
