import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "forest-green": "#3D7A5C",
        "deep-green": "#1C3A2A",
        "light-green": "#EAF5EE",
        "sage-border": "#D4E8DC",
        "bg-main": "#FAFDF9",
        "secondary-text": "#6B8F78",
        "rose-powder": "#E8C4B8",
        "terracotta": "#C4826A",
        "primary": "#3D7A5C",
        "primary-dark": "#226145",
        "primary-container": "#3D7A5C",
        "on-primary": "#ffffff",
        "on-primary-container": "#EAF5EE",
        "primary-fixed": "#B0F1CC",
        "primary-fixed-dim": "#95D4B1",
        "inverse-primary": "#95D4B1",
        "secondary": "#74584F",
        "on-secondary": "#ffffff",
        "secondary-container": "#E8C4B8",
        "on-secondary-container": "#5A4138",
        "secondary-fixed": "#FFE0D4",
        "secondary-fixed-dim": "#E2BFB3",
        "tertiary": "#C4826A",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#9B5F49",
        "on-tertiary-container": "#FFEFEA",
        "tertiary-fixed": "#FFE0D4",
        "tertiary-fixed-dim": "#C4826A",
        "surface": "#FAFDF9",
        "surface-dim": "#D4E8DC",
        "surface-bright": "#FAFDF9",
        "surface-variant": "#D4E8DC",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#EAF5EE",
        "surface-container": "#EAF5EE",
        "surface-container-high": "#D4E8DC",
        "surface-container-highest": "#C8EBDA",
        "on-surface": "#1C3A2A",
        "on-surface-variant": "#6B8F78",
        "surface-tint": "#3D7A5C",
        "background": "#FAFDF9",
        "on-background": "#1C3A2A",
        "outline": "#6B8F78",
        "outline-variant": "#D4E8DC",
        "inverse-surface": "#1C3A2A",
        "inverse-on-surface": "#EAF5EE",
        "error": "#C4826A",
        "on-error": "#ffffff",
        "error-container": "#FFE0D4",
        "on-error-container": "#7E1D00",
      },
      fontFamily: {
        heading: ["var(--font-heading)", "Georgia", "serif"],
        body: ["var(--font-body)", "system-ui", "sans-serif"],
        ui: ["var(--font-ui)", "system-ui", "sans-serif"],
        serif: ["var(--font-heading)", "Georgia", "serif"],
        sans: ["var(--font-body)", "system-ui", "sans-serif"],
      },
      fontSize: {
        display: ["56px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        h1: ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        h2: ["36px", { lineHeight: "1.3", fontWeight: "600" }],
        h3: ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        h4: ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-xs": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        "2xl": "32px",
        full: "9999px",
        card: "16px",
        button: "99px",
      },
      spacing: {
        xs: "8px",
        sm: "16px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        gutter: "24px",
      },
      boxShadow: {
        card: "0 0 0 1px rgba(28, 58, 42, 0.05), 0 2px 12px rgba(28, 58, 42, 0.06)",
        "card-hover": "0 0 0 1px rgba(28, 58, 42, 0.08), 0 6px 24px rgba(28, 58, 42, 0.10)",
        nav: "0 1px 8px rgba(28, 58, 42, 0.08)",
        modal: "0 8px 48px rgba(28, 58, 42, 0.18)",
        button: "0 2px 8px rgba(61, 122, 92, 0.22)",
      },
      keyframes: {
        breathe: {
          "0%, 100%": { transform: "scale(1)", opacity: "0.6" },
          "50%": { transform: "scale(1.08)", opacity: "0.9" },
        },
        "slide-up": {
          "0%": { transform: "translateY(100%)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "slide-down": {
          "0%": { transform: "translateY(-60px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "fade-up": {
          "0%": { transform: "translateY(30px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "skeleton-pulse": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        ripple: {
          "0%": { transform: "scale(0)", opacity: "0.4" },
          "100%": { transform: "scale(2.5)", opacity: "0" },
        },
        "live-pulse": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.5", transform: "scale(0.8)" },
        },
      },
      animation: {
        breathe: "breathe 4s ease-in-out infinite",
        "breathe-slow": "breathe 8s ease-in-out infinite",
        "slide-up": "slide-up 0.4s ease-out",
        "slide-down": "slide-down 0.5s ease-out",
        "fade-up": "fade-up 0.7s ease-out",
        "skeleton-pulse": "skeleton-pulse 1.5s ease-in-out infinite",
        ripple: "ripple 0.6s ease-out",
        "live-pulse": "live-pulse 2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
